noinst_LTLIBRARIES = libbasemonitors.la

libbasemonitors_la_CPPFLAGS = -I$(top_srcdir)/src/include

libbasemonitors_la_SOURCES = ValueTraceMonitor.cc			\
TraceMonitorFactory.cc ValueMeanMonitor.cc MeanMonitorFactory.cc	\
ValueVarMonitor.cc VarianceMonitorFactory.cc

noinst_HEADERS = ValueTraceMonitor.h TraceMonitorFactory.h	\
ValueMeanMonitor.h MeanMonitorFactory.h ValueVarMonitor.h	\
VarianceMonitorFactory.h
