noinst_LTLIBRARIES = libbasemonitors.la

libbasemonitors_la_CPPFLAGS = -I$(top_srcdir)/src/include

libbasemonitors_la_SOURCES = ValueTraceMonitor.cc ValueMeanMonitor.cc	\
ValueVarMonitor.cc ValueMonitorFactory.cc

noinst_HEADERS = ValueTraceMonitor.h ValueMeanMonitor.h	\
ValueVarMonitor.h ValueMonitorFactory.h
