modelincludedir = $(pkgincludedir)/model

modelinclude_HEADERS = SymTab.h NodeArray.h Model.h Monitor.h		\
BUGSModel.h MonitorFactory.h MonitorControl.h MonitorInfo.h		\
NodeArraySubset.h StochasticIndex.h TraceMonitor.h MeanMonitor.h	\
VarMonitor.h WeightedTraceMonitor.h CovMonitor.h		\
MonitorStat.h WeightMonitor.h TraceWeight.h ESSWeight.h

